### ISSUE TITLE
Update website to reflect move to manchester

### ISSUE THREAD

**Issue by rafaelcaue** [autonomy-and-verification/autonomy-and-verification.github.io#3]
The website needs updating to reflect that Michael, Clare, and Louise plus most of the RAs have moved to Manchester.

I propose that we systematically judge what needs doing to each page, then check to make sure that all looks consistent. The changes should only really take a day, but there is also the matter of the location of the website to organise (which I'm still talking to Chris Page about).

**Comment by mluckcuck** [comment]
Is this done?
Have we decided that this website stays on github, while the new Group website will be the UoM page?

**Comment by rafaelcaue** [comment]
I think so.

As far as I know that was the plan.
